name: monarchic_agent_protocol
description: Monarchic Agent Protocol protobuf bindings for Dart.
version: v0.1.3
repository: https://github.com/monarchic-ai/monarchic-agent-protocol
homepage: https://github.com/monarchic-ai/monarchic-agent-protocol

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  protobuf: ^3.1.0
